version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
    env_file:
      - .env
    mem_limit: 12gb # Adjust memory limit as needed
    stdin_open: true # Equivalent to -i
    tty: true # Equivalent to -t
    entrypoint: python main.py
    environment:
      - DEBUG_TABLE=compiled_contracts
      - DEBUG_OFFSET=100000
